const KEY="kmq_v6";let S=JSON.parse(localStorage.getItem(KEY)||'{"xp":0,"offering":300,"found":[],"met":[],"items":{},"answered":{}}');let pos={x:49,y:74},nearS=null,nearN=null,current=null,locked=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(S));stats()}function stats(){$("#xp").textContent=S.xp;$("#lv").textContent=Math.floor(S.xp/100)+1;$("#offering").textContent=S.offering;$("#mapOffering").textContent=S.offering;$("#gachaMoney").textContent=S.offering}
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1600)}
function show(id){$$(".page").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");window.scrollTo(0,0);stats();if(id==="world")setTimeout(update,0);if(id==="collection")collection();if(id==="quests")quests();if(id==="history")history()}
function dist(el){let r=el.getBoundingClientRect(),m=$("#map").getBoundingClientRect();return Math.hypot(pos.x-(r.left+r.width/2-m.left)/m.width*100,pos.y-(r.top+r.height/2-m.top)/m.height*100)}
function update(){$("#player").style.left=pos.x+"%";$("#player").style.top=pos.y+"%";let a=999,b=999;nearS=nearN=null;$$(".spot").forEach(e=>{let d=dist(e);if(d<a){a=d;nearS=e.dataset.spot}});$$(".npc").forEach(e=>{let d=dist(e);if(d<b){b=d;nearN=e.dataset.npc}});$("#talk").disabled=b>=13;$("#inspect").disabled=a>=13;if(b<13){$("#nearName").textContent=NPCS[nearN].name;$("#nearText").textContent="話しかけられる"}else if(a<13){$("#nearName").textContent=SPOTS[nearS].name;$("#nearText").textContent="調べられる"}else{$("#nearName").textContent="中央通り";$("#nearText").textContent="街を歩いてみよう"}}
function move(x,y){pos.x=Math.max(5,Math.min(95,pos.x+x));pos.y=Math.max(5,Math.min(95,pos.y+y));update()}
$$("[data-m]").forEach(e=>e.onclick=()=>{let d=e.dataset.m;move(d==="left"?-4:d==="right"?4:0,d==="up"?-4:d==="down"?4:0)});document.addEventListener("keydown",e=>{if(!$("#world").classList.contains("active"))return;let k=e.key.toLowerCase();if(k==="w"||k==="arrowup")move(0,-4);if(k==="s"||k==="arrowdown")move(0,4);if(k==="a"||k==="arrowleft")move(-4,0);if(k==="d"||k==="arrowright")move(4,0)});
$("#talk").onclick=()=>{let n=NPCS[nearN];if(!S.met.includes(nearN)){S.met.push(nearN);S.xp+=10;save()}$("#dialogBox").innerHTML=`<div class="dialog"><div class="pixelFace">☺</div><h2>${n.name}</h2><p>${n.text}</p><button class="primary big" id="challenge">クイズに挑戦</button><button class="secondary big" onclick="show('world')">街へ戻る</button></div>`;$("#challenge").onclick=()=>openQuiz(n.spot);show("dialog")};
$("#inspect").onclick=()=>{if(!S.found.includes(nearS)){S.found.push(nearS);S.xp+=15;save();toast("新しい場所を発見！ +15XP")}openQuiz(nearS)};
function openQuiz(id){current={id,...SPOTS[id]};locked=false;$("#quizTitle").textContent=current.name;$("#quizBox").innerHTML=`<div class="quizcard"><span class="tag">祭りクイズ</span><h2>${current.q}</h2><div class="answers">${current.a.map((x,i)=>`<button data-a="${i}">${x}</button>`).join("")}</div><div id="ex"></div></div>`;$$("[data-a]").forEach(e=>e.onclick=()=>answer(+e.dataset.a));show("quiz")}
function answer(i){if(locked)return;locked=true;let bs=$$("[data-a]");bs[current.ok].classList.add("correct");let first=!S.answered[current.id];if(i===current.ok){if(first){S.offering+=100;S.xp+=30;S.answered[current.id]=1;toast("正解！ お布施 +100")}else{S.offering+=20;S.xp+=10;toast("正解！ 復習ボーナス +20")}}else{bs[i].classList.add("wrong");toast("惜しい！ 解説を確認しよう")}$("#ex").innerHTML=`<div class="ex"><b>解説</b><p>${current.ex}</p><button class="primary big" onclick="show('world')">探索へ戻る</button></div>`;save()}
function weighted(){let total=ITEMS.reduce((s,x)=>s+x.weight,0),r=Math.random()*total;for(let x of ITEMS){r-=x.weight;if(r<=0)return x}return ITEMS.at(-1)}
function pull(n,cost){if(S.offering<cost){toast("お布施が足りない！");return}S.offering-=cost;let got=[];for(let i=0;i<n;i++){let x=weighted();S.items[x.name]=(S.items[x.name]||0)+1;got.push(x)}save();$("#capsule").classList.remove("pop");void $("#capsule").offsetWidth;$("#capsule").classList.add("pop");$("#capsule").textContent=got[0].icon;$("#gachaResult").innerHTML=got.map(x=>`<div class="result ${x.rarity}"><b>${x.rarity}</b> ${x.icon} ${x.name}</div>`).join("");toast(n+"回ガチャ！")}
$("#pull").onclick=()=>pull(1,100);$("#pull10").onclick=()=>pull(10,900);
function collection(){$("#collectionBox").innerHTML=ITEMS.map(x=>`<article class="${x.rarity}"><div class="itemIcon">${x.icon}</div><b>${x.rarity} ${x.name}</b><small>所持 ${S.items[x.name]||0}</small></article>`).join("")}
function quests(){$("#questBox").innerHTML=`<article><h3>🏮 六軒町を発見</h3><b>${S.found.includes("rokken")?"達成！":"未達成"}</b></article><article><h3>🥁 今福囃子を発見</h3><b>${S.found.includes("imafuku")?"達成！":"未達成"}</b></article><article><h3>👥 NPC全員と話す</h3><b>${S.met.length}/3</b></article><article><h3>🗺 全スポット発見</h3><b>${S.found.length}/5</b></article><article><h3>🎁 ガチャ景品を集める</h3><b>${Object.keys(S.items).length}/${ITEMS.length}種類</b></article>`}
function history(){$("#historyBox").innerHTML=HISTORY.map(x=>`<article><span class="tag">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("")}
$("#gear").onclick=()=>$("#modal").classList.remove("hidden");$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#reset").onclick=()=>{localStorage.removeItem(KEY);location.reload()};stats();