const KEY="kmq_v7";let S=JSON.parse(localStorage.getItem(KEY)||'{"xp":0,"money":0,"book":[],"quests":[],"items":{},"met":[]}');let p={x:49,y:58},near=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(S));stats()}
function stats(){let lv=Math.floor(S.xp/100)+1;$("#lv").textContent=lv;$("#xp").textContent=S.xp%100;$("#money").textContent=S.money;$("#bookCount").textContent=S.book.length;$("#questCount").textContent=S.quests.length;$("#expbar").style.width=(S.xp%100)+"%"}
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1400)}
function dist(e){let r=e.getBoundingClientRect(),w=$("#world").getBoundingClientRect();return Math.hypot(p.x-(r.left+r.width/2-w.left)/w.width*100,p.y-(r.top+r.height/2-w.top)/w.height*100)}
function update(){$("#player").style.left=p.x+"%";$("#player").style.top=p.y+"%";$("#dot").style.left=p.x+"%";$("#dot").style.top=p.y+"%";let d=999;near=null;$$(".npc").forEach(e=>{let x=dist(e);if(x<d){d=x;near=e.dataset.npc}});$("#player em").style.display=d<12?"block":"none"}
function move(dx,dy){p.x=Math.max(3,Math.min(94,p.x+dx));p.y=Math.max(5,Math.min(92,p.y+dy));update()}
$$("[data-m]").forEach(b=>b.onclick=()=>{let d=b.dataset.m;move(d==="left"?-3:d==="right"?3:0,d==="up"?-3:d==="down"?3:0)});
document.addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(k==="w"||k==="arrowup")move(0,-3);if(k==="s"||k==="arrowdown")move(0,3);if(k==="a"||k==="arrowleft")move(-3,0);if(k==="d"||k==="arrowright")move(3,0);if(k==="enter"||k===" ")interact()});
$("#A").onclick=interact;
function interact(){if(!near){toast("人に近づいてみよう");return}let n=NPCS[near];if(!S.met.includes(near)){S.met.push(near);S.xp+=10;save()}$("#speaker").textContent=n.name;$("#speech").textContent=n.text;$("#dialog").classList.remove("hidden");$("#yes").onclick=()=>quiz(near);$("#no").onclick=()=>$("#dialog").classList.add("hidden")}
function quiz(id){let n=NPCS[id];$("#dialog").classList.add("hidden");open(`<h2>${n.name}のクイズ</h2><p>${n.q}</p><div class="answers">${n.a.map((x,i)=>`<button data-q="${i}">${x}</button>`).join("")}</div><div id="ex"></div>`);$$("[data-q]").forEach(b=>b.onclick=()=>{let i=+b.dataset.q,buttons=$$("[data-q]");buttons[n.ok].classList.add("correct");if(i===n.ok){let first=!S.book.includes(id);if(first){S.book.push(id);S.money+=100;S.xp+=35;toast("正解！祭り札100枚！")}else{S.money+=20;S.xp+=10;toast("復習正解！20枚！")}if(!S.quests.includes(id))S.quests.push(id)}else{buttons[i].classList.add("wrong");toast("惜しい！")}$("#ex").innerHTML=`<div class="card">${n.ex}</div>`;save()})}
function open(html){$("#windowBody").innerHTML=html;$("#overlay").classList.remove("hidden")}$("#x").onclick=()=>$("#overlay").classList.add("hidden");
function gacha(){open(`<h2>🎁 祭り札ガチャ</h2><p>祭り札100枚で1回。コレクションを集めよう。</p><div class="gachaBall">🔮</div><button id="pull" class="gachaBtn">100枚でガチャ</button><div id="result"></div>`);$("#pull").onclick=()=>{if(S.money<100){toast("祭り札が足りない");return}S.money-=100;let total=ITEMS.reduce((a,x)=>a+x[3],0),r=Math.random()*total,item;for(let x of ITEMS){r-=x[3];if(r<=0){item=x;break}}S.items[item[1]]=(S.items[item[1]]||0)+1;$("#result").innerHTML=`<div class="card ${item[0]}"><h2>${item[0]} ${item[2]}</h2><b>${item[1]}</b><p>所持 ${S.items[item[1]]}</p></div>`;save()}}
function book(){open(`<h2>📖 図鑑</h2>${Object.keys(NPCS).map(k=>`<div class="card">${S.book.includes(k)?"📖 "+NPCS[k].name+"<br>"+NPCS[k].ex:"🔒 ？？？"}</div>`).join("")}`)}
function quests(){open(`<h2>📜 クエスト</h2><div class="card">人に話しかける：${S.met.length}/3</div><div class="card">クイズをクリア：${S.quests.length}/3</div><div class="card">図鑑を集める：${S.book.length}/7</div>`)}
function bag(){open(`<h2>💰 もちもの</h2><div class="card">🎟 祭り札 ${S.money}枚</div>${ITEMS.map(x=>`<div class="card ${x[0]}">${x[2]} ${x[1]} × ${S.items[x[1]]||0}</div>`).join("")}`)}
function settings(){open(`<h2>⚙ せってい</h2><p>スマホ：十字キーとAボタン<br>PC：WASD / 矢印キー、Enter</p><button id="reset" class="gachaBtn">セーブをリセット</button>`);$("#reset").onclick=()=>{localStorage.removeItem(KEY);location.reload()}}
$$("[data-tab]").forEach(b=>b.onclick=()=>({gacha,book,quests,bag,settings}[b.dataset.tab]||settings)());$("#saveBtn").onclick=()=>{save();toast("セーブしました")};stats();update();